[book]
title = "KSS-PC-Club docs"
author = "KSS-PC-Club"
description = "KSS PC Club の部活内ドキュメント"
language = "ja"
multilingual = false
src = "src"

[output.html]
additional-css = ["src/magazine/2022/contents/custom.css"]
git-repository-url = "https://github.com/kss-pc-club/doc"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/kss-pc-club/doc/tree/main/{path}"
mathjax-support = true
cname = "doc.kss-pc.club"
input-404 = "404.md"