[book]
title = "KSS-PC-Club docs"
author = "KSS-PC-Club"
description = "KSS PC Club の部活内ドキュメント"
language = "ja"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/kss-pc-club/doc"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/kss-pc-club/doc/{path}"